### ISSUE TITLE
@GetMapping("/message/id/{id}")

### ISSUE THREAD

**Issue by jakekali** [CooperCrew/crew-connect#63]
In src/main/java/com/coopercrew/crewconnect/web/UserController.java
The @GetMapping("/message/id/{id}") function, looks like to me a get users in a group chat? seems like the url path doesn't match?

can we change? are the dependencies that would also need to be refactored?

**Comment by johnpl-io** [comment]
Yes we can change that it is not that much refactoring

**Comment by johnpl-io** [comment]
fixed
